### PR TITLE
Indent first line of each paragraph after the first one

### PR DESCRIPTION
**Pull request by benhid**
Also implements https://github.com/vincentdoerig/latex-css/pull/5

### CODE REVIEW

**Comment by vincentdoerig** [comment]
As mentioned before, if you wrap each section in a `<section>` tag, it will mess up the vertical spacing. Is there a way to fix that?

**Comment by benhid** [comment]
I think I've fixed the spacing. Also, note that `<div class="footnotes"></div>` has been replaced by `<footer></footer>` to promote the "class-less" filosofy of this library. What do you think?

**Comment by vincentdoerig** [comment]
Could you please revert all the formatting changes as it makes it very difficult to actually see what you implemented. Cheers!

**Comment by vincentdoerig** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
