### PR TITLE
Add 2px blue focus-frame (accessibility) and danish language file

### PR DESCRIPTION
**Pull request by oleguldberg**
Using the keyboard to navigate (tab-key and/or accessive technology) having a focus highlight is very helpfull. So, this change adds a 2px blue focus frame.

### CODE REVIEW

**Comment by vincentdoerig** [comment]
Thanks. Just one small critisim, the blue property doesn't go too well on the eyes in my opinion, would you mind changing it to something a bit darker, `hsl(222, 68%, 35%)` for example?

**Comment by oleguldberg** [comment]
The outline-offset is great - adds readablity. 

Colour is alway a point of discussion - I tend to favor the lighter blue as the darker blue is allmost black. I ave added your darker blue - it might grow on me *smile*

**Comment by vincentdoerig** [comment]
Fair enough haha. I might have changed my mind again sorry, I actually really like how this looks (taken and adapted from the [W3C website](https://www.w3.org/WAI/WCAG21/Techniques/css/C15). What do you think? 
image

```css
a:focus {
  background: hsla(0, 0%, 75%, 0.25);
  border-bottom: 3px solid hsl(0, 0%, 45%);
  text-decoration: none;
}
```

**Comment by oleguldberg** [comment]
slick .. might bitch about the colour later *grin*.

Thanks a bunch!

**Comment by oleguldberg** [comment]
Damn - the "bottom line" will disapear when you "tab" to the bottom of the page:

image

image

so, I prefer the "box" to the underlined version.

**Comment by vincentdoerig** [comment]
Alright, so we are revisiting the boxed outline. You mentioned it being too dark, how about `hsl(220, 90%, 52%)`, similar to `blue` but a bit less "aggressive".

image 
vs
image

**Comment by oleguldberg** [comment]
Amazing - Thats great!
The box is readable and the colour is great!

**Pull request merged**
